### ISSUE TITLE
Py4JJavaError 

### ISSUE THREAD

**Issue by cs201503** [oap-project/raydp#114]
Hi,
while trying out the example "Titanic survival prediction with RayDp", I ran into the following problem when running the step:

`app_name = "Titanic survival prediction with RayDp"
num_executors = 2
cores_per_executor = 1
memory_per_executor = "1GB"
spark = raydp.init_spark(app_name, num_executors, cores_per_executor, memory_per_executor)`

```
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-3-478be455a428> in <module>
      3 cores_per_executor = 1
      4 memory_per_executor = "1GB"
----> 5 spark = raydp.init_spark(app_name, num_executors, cores_per_executor, memory_per_executor)

/usr/local/lib/python3.8/dist-packages/raydp/context.py in init_spark(app_name, num_executors, executor_cores, executor_memory, configs)
    120                 _global_spark_context = _SparkContext(
    121                     app_name, num_executors, executor_cores, executor_memory, configs)
--> 122                 return _global_spark_context.get_or_create_session()
    123             except:
    124                 _global_spark_context = None

/usr/local/lib/python3.8/dist-packages/raydp/context.py in get_or_create_session(self)
     66         if self._spark_session is not None:
     67             return self._spark_session
---> 68         spark_cluster = self._get_or_create_spark_cluster()
     69         self._spark_session = spark_cluster.get_spark_session(
     70             self._app_name,

/usr/local/lib/python3.8/dist-packages/raydp/context.py in _get_or_create_spark_cluster(self)
     60         if self._spark_cluster is not None:
     61             return self._spark_cluster
---> 62         self._spark_cluster = SparkCluster()
     63         return self._spark_cluster
     64 

/usr/local/lib/python3.8/dist-packages/raydp/spark/ray_cluster.py in __init__(self)
     29         super().__init__(None)
     30         self._app_master_bridge = None
---> 31         self._set_up_master(None, None)
     32         self._spark_session: SparkSession = None
     33 

/usr/local/lib/python3.8/dist-packages/raydp/spark/ray_cluster.py in _set_up_master(self, resources, kwargs)
     35         # TODO: specify the app master resource
     36         self._app_master_bridge = RayClusterMaster()
---> 37         self._app_master_bridge.start_up()
     38 
     39     def _set_up_worker(self, resources: Dict[str, float], kwargs: Dict[str, str]):

/usr/local/lib/python3.8/dist-packages/raydp/spark/ray_cluster_master.py in start_up(self, popen_kwargs)
     54         self._set_properties()
     55         self._host = ray._private.services.get_node_ip_address()
---> 56         self._create_app_master(extra_classpath)
     57         self._started_up = True
     58 

/usr/local/lib/python3.8/dist-packages/raydp/spark/ray_cluster_master.py in _create_app_master(self, extra_classpath)
    162         if self._started_up:
    163             return
--> 164         self._app_master_java_bridge.startUpAppMaster(extra_classpath)
    165 
    166     def get_master_url(self):

/usr/local/lib/python3.8/dist-packages/py4j/java_gateway.py in __call__(self, *args)
   1302 
   1303         answer = self.gateway_client.send_command(command)
-> 1304         return_value = get_return_value(
   1305             answer, self.gateway_client, self.target_id, self.name)
   1306 

/usr/local/lib/python3.8/dist-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    324             value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325             if answer[1] == REFERENCE_TYPE:
--> 326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
    328                     format(target_id, ".", name), value)

Py4JJavaError: An error occurred while calling o0.startUpAppMaster.
: java.lang.RuntimeException: Failed to initialize Ray runtime.
	at io.ray.api.Ray.init(Ray.java:27)
	at org.apache.spark.deploy.raydp.AppMasterJavaBridge.startUpAppMaster(AppMasterJavaBridge.scala:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to initialize ray runtime
	at io.ray.runtime.DefaultRayRuntimeFactory.createRayRuntime(DefaultRayRuntimeFactory.java:43)
	at io.ray.api.Ray.init(Ray.java:38)
	at io.ray.api.Ray.init(Ray.java:25)
	... 12 more
Caused by: java.lang.RuntimeException: Failed to get address info. Output: null
	at io.ray.runtime.runner.RunManager.getAddressInfoAndFillConfig(RunManager.java:90)
	at io.ray.runtime.RayNativeRuntime.start(RayNativeRuntime.java:88)
	at io.ray.runtime.DefaultRayRuntimeFactory.createRayRuntime(DefaultRayRuntimeFactory.java:39)
	... 14 more
Caused by: java.io.IOException: Cannot run program "python": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at io.ray.runtime.runner.RunManager.runCommand(RunManager.java:105)
	at io.ray.runtime.runner.RunManager.getAddressInfoAndFillConfig(RunManager.java:80)
	... 16 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 18 more
```
I checked the closed issues before, and I already changed my JDK version to 
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

Can you please help me?
Thank you!

**Comment by kira-lin** [comment]
Hi,
It seems like you don't have python installed. Maybe you only have python3, but no python? In that case you can try create a symbolic link.

**Comment by cs201503** [comment]
> Hi,
> It seems like you don't have python installed. Maybe you only have python3, but no python? In that case you can try create a symbolic link.

Hi Kira,
thank you. I have created the link. It seems to be solved.
