### ISSUE TITLE
Failed to create RayClusterMaster since global worker doesn't have node attr

### ISSUE THREAD

**Issue by Jeffwan** [oap-project/raydp#130]
### Problem

I submit a simple spark example to RayCluster on Kubernetes and meet this problem. 

```
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Traceback (most recent call last):
  File "raydp-spark.py", line 15, in <module>
    executor_memory='1G')
  File "/home/ray/anaconda3/lib/python3.7/site-packages/raydp/context.py", line 122, in init_spark
    return _global_spark_context.get_or_create_session()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/raydp/context.py", line 68, in get_or_create_session
    spark_cluster = self._get_or_create_spark_cluster()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/raydp/context.py", line 62, in _get_or_create_spark_cluster
    self._spark_cluster = SparkCluster()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/raydp/spark/ray_cluster.py", line 32, in __init__
    self._set_up_master(None, None)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/raydp/spark/ray_cluster.py", line 38, in _set_up_master
    self._app_master_bridge.start_up()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/raydp/spark/ray_cluster_master.py", line 55, in start_up
    self._set_properties()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/raydp/spark/ray_cluster_master.py", line 144, in _set_properties
    options["ray.node-ip"] = node.node_ip_address
AttributeError: 'NoneType' object has no attribute 'node_ip_address'
```

Looks like `ray.worker.global_worker.node` return `None` and `_set_properties` failed afterwards. 

https://github.com/oap-project/raydp/blob/91f48c9279cf1dc9f2740932f5664ceed0118759/python/raydp/spark/ray_cluster_master.py#L141

I am new to ray and not sure if this is a RayDP issue or Ray environment issue? 

### Environment

I follow ray instruction and use Ray operator to spin up an example cluster in my environment. 

### Job Spec

```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: raydp-spark-
  namespace: ray
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ray
          image: seedjeffwan/ray:0.1
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "wget https://gist.githubusercontent.com/Jeffwan/e10c08dcd4aa2751c361e136896bc35f/raw/9d7a8558290768b042f85695aa509aa35874571f/raydp-spark.py &&
              python raydp-spark.py"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
```

### RayDP code

```
import os
import ray
import raydp

HEAD_SERVICE_IP_ENV = "EXAMPLE_CLUSTER_RAY_HEAD_SERVICE_HOST"
HEAD_SERVICE_CLIENT_PORT_ENV = "EXAMPLE_CLUSTER_RAY_HEAD_SERVICE_PORT_CLIENT"

head_service_ip = os.environ[HEAD_SERVICE_IP_ENV]
client_port = os.environ[HEAD_SERVICE_CLIENT_PORT_ENV]
ray.util.connect(f"{head_service_ip}:{client_port}")

spark = raydp.init_spark('word_count',
                         num_executors=2,
                         executor_cores=2,
                         executor_memory='1G')

df = spark.createDataFrame([('look',), ('spark',), ('tutorial',), ('spark',), ('look', ), ('python', )], ['word'])
df.show()
word_count = df.groupBy('word').count()
word_count.show()

raydp.stop_spark()
```

**Comment by ConeyLiu** [comment]
Hi @Jeffwan, it seems like you connect to the ray cluster with ray client. What happens with the following code?

```python
@ray.remote
class SparkCluster:
    def __init__(self):
        self.spark = None
    def start(self):
        self.spark = raydp.init_spark('word_count',
                                       num_executors=2,
                                       executor_cores=2,
                                       executor_memory='1G')

    def run(self):
        df = self.spark.createDataFrame([('look',), ('spark',), ('tutorial',), ('spark',), ('look', ), ('python', )], ['word'])
        df.show()
        word_count = df.groupBy('word').count()
        word_count.show()

    def stop(self):
        raydp.stop_spark()
    
 
spark = SparkCluster.remote()
ray.get(spark.start.remote())
ray.get(spark.run.remote())
ray.get(spark.stop.remote())
```

**Comment by Jeffwan** [comment]
Thanks @ConeyLiu  I tried your example and see following issues.  `details = "Exception iterating responses: No module named 'raydp'"`  The image for ray workers in my kubernetes cluster does have `raydp` package.   Do you have any insight? 


```
2021-04-07 19:40:38 (16.7 MB/s) - ‘raydp-spark-remote.py’ saved [765/765]

Traceback (most recent call last):
  File "raydp-spark-remote.py", line 24, in <module>
    spark = SparkCluster.remote()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 413, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 590, in _remote
    worker.check_connected()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 204, in check_connected
    raise RaySystemError("Ray has not been started yet. You can "
ray.exceptions.RaySystemError: System error: Ray has not been started yet. You can start Ray with 'ray.init()'.
➜  ray git:(master) ✗ k logs -f raydp-spark-remoteqzrjs-gwnzj
--2021-04-07 19:08:55--  https://gist.githubusercontent.com/Jeffwan/237652be53a5cfbe8dbccbfe2e3c468e/raw/232197cf030108524b2243915b14d592af3ae050/raydp-spark-remote.py
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1075 (1.0K) [text/plain]
Saving to: ‘raydp-spark-remote.py’

     0K .                                                     100% 10.6M=0s

2021-04-07 19:08:55 (10.6 MB/s) - ‘raydp-spark-remote.py’ saved [1075/1075]

The autoscaler failed with the following error:
Terminated with signal 15
  File "/home/ray/anaconda3/bin/ray-operator", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/ray_operator/operator.py", line 154, in main
    handle_event(event_type, cluster_cr, cluster_name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/ray_operator/operator.py", line 113, in handle_event
    cluster_action(event_type, cluster_cr, cluster_name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/ray_operator/operator.py", line 127, in cluster_action
    ray_clusters[cluster_name].create_or_update()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/ray_operator/operator.py", line 50, in create_or_update
    self.do_in_subprocess(self._create_or_update)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/ray_operator/operator.py", line 40, in do_in_subprocess
    self.subprocess.start()
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/ray/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/ray_operator/operator.py", line 54, in _create_or_update
    self.start_monitor()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/ray_operator/operator.py", line 79, in start_monitor
    self.mtr.run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 285, in run
    self._run()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/monitor.py", line 187, in _run
    self.autoscaler.update()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 140, in update
    self._update()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 323, in _update
    self.recover_if_needed(node_id, now)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 576, in recover_if_needed
    if not self.can_update(node_id):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 712, in can_update
    if not self.launch_config_ok(node_id):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/autoscaler.py", line 543, in launch_config_ok
    node_tags = self.provider.node_tags(node_id)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/_kubernetes/node_provider.py", line 70, in node_tags
    pod = core_api().read_namespaced_pod(node_id, self.namespace)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 22785, in read_namespaced_pod
    return self.read_namespaced_pod_with_http_info(name, namespace, **kwargs)  # noqa: E501
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/api/core_v1_api.py", line 22894, in read_namespaced_pod_with_http_info
    collection_formats=collection_formats)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 353, in call_api
    _preload_content, _request_timeout, _host)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 192, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 260, in deserialize
    data = json.loads(response.data)
  File "/home/ray/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/ray/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ray/anaconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)

Got Error from data channel -- shutting down: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: No module named 'raydp'"
	debug_error_string = "{"created":"@1617847736.612458200","description":"Error received from peer ipv4:10.99.2.122:10001","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: No module named 'raydp'","grpc_status":2}"
>
Traceback (most recent call last):
  File "raydp-spark-remote.py", line 32, in <module>
    spark = SparkCluster.remote()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 413, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py", line 587, in _remote
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ray/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 90, in _data_main
    raise e
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 64, in _data_main
    for response in resp_stream:
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating responses: No module named 'raydp'"
	debug_error_string = "{"created":"@1617847736.612458200","description":"Error received from peer ipv4:10.99.2.122:10001","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception iterating responses: No module named 'raydp'","grpc_status":2}"
>

    override_environment_variables))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 91, in client_mode_convert_actor
    return client_actor._remote(in_args, in_kwargs, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/common.py", line 183, in _remote
    return self.options(**option_args).remote(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/common.py", line 296, in remote
    ref_ids = ray.call_remote(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 96, in call_remote
    return self.worker.call_remote(instance, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 289, in call_remote
    task = instance._prepare_client_task()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/common.py", line 289, in _prepare_client_task
    task = self.remote_stub._prepare_client_task()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/common.py", line 194, in _prepare_client_task
    self._ensure_ref()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/common.py", line 167, in _ensure_ref
    self.actor_cls, client_ref_id=self._client_side_ref.id)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/api.py", line 45, in put
    return self.worker.put(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 233, in put
    out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 233, in <listcomp>
    out = [self._put(x, client_ref_id=client_ref_id) for x in to_put]
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/worker.py", line 250, in _put
    resp = self.data_client.PutObject(req)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 149, in PutObject
    resp = self._blocking_send(datareq)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/client/dataclient.py", line 109, in _blocking_send
    "Cannot send request due to data channel "
ConnectionError: Cannot send request due to data channel shutting down. Request: req_id: 3
put {
  data: "\200\005\225\324\007\000\000\000\000\000\000\214\033ray.cloudpickle.cloudpickle\224\214\024_make_skeleton_class\224\223\224(\214\010builtins\224\214\004type\224\223\224\214\014SparkCluster\224h\002(h\005h\006h\003\214\006object\224\223\224\205\224}\224\214 20cced19868e46ab9f2ef97f8685ba12\224Nt\224R\224\214 ray.cloudpickle.cloudpickle_fast\224\214\017_class_setstate\224\223\224h\r}\224(\214\n__module__\224\214\010__main__\224\214\010__init__\224h\000\214\r_builtin_type\224\223\224\214\nLambdaType\224\205\224R\224(h\026\214\010CodeType\224\205\224R\224(K\001K\000K\001K\002KCC\nd\000|\000_\000d\000S\000\224N\205\224\214\005spark\224\205\224\214\004self\224\205\224\214\025raydp-spark-remote.py\224h\024K\016C\002\000\001\224))t\224R\224}\224(\214\013__package__\224N\214\010__name__\224h\023\214\010__file__\224\214\025raydp-spark-remote.py\224uNNNt\224R\224h\016\214\022_function_setstate\224\223\224h-}\224}\224(h)h\024\214\014__qualname__\224\214\025SparkCluster.__init__\224\214\017__annotations__\224}\224\214\016__kwdefaults__\224N\214\014__defaults__\224Nh\022h\023\214\007__doc__\224N\214\013__closure__\224N\214\027_cloudpickle_submodules\224]\224\214\013__globals__\224}\224u\206\224\206R0\214\005start\224h\031(h\034(K\001K\000K\001K\006KCC\030t\000j\001d\001d\002d\002d\003d\004\215\004|\000_\002d\000S\000\224(N\214\nword_count\224K\002\214\0021G\224\214\rnum_executors\224\214\016executor_cores\224\214\017executor_memory\224\207\224t\224\214\005raydp\224\214\ninit_spark\224h\037\207\224h!\205\224h#h?K\020C\010\000\001\006\001\002\001\002\001\224))t\224R\224h\'NNNt\224R\224h/hP}\224}\224(h)h?h2\214\022SparkCluster.start\224h4}\224h6Nh7Nh\022h\023h8Nh9Nh:]\224h\000\214\tsubimport\224\223\224\214\013raydp.spark\224\205\224R\224ah<}\224hHhWhH\205\224R\224su\206\224\206R0\214\003run\224h\031(h\034(K\001K\000K\003K\010KCC>|\000j\000\240\001d\001d\002d\003d\002d\001d\004g\006d\005g\001\241\002}\001|\001\240\002\241\000\001\000|\001\240\003d\005\241\001\240\004\241\000}\002|\002\240\002\241\000\001\000d\000S\000\224(N\214\004look\224\205\224h\037\205\224\214\010tutorial\224\205\224\214\006python\224\205\224\214\004word\224t\224(h\037\214\017createDataFrame\224\214\004show\224\214\007groupBy\224\214\005count\224t\224h!\214\002df\224hA\207\224h#h_K\026C\010\000\001\034\001\010\001\016\001\224))t\224R\224h\'NNNt\224R\224h/hu}\224}\224(h)h_h2\214\020SparkCluster.run\224h4}\224h6Nh7Nh\022h\023h8Nh9Nh:]\224h<}\224u\206\224\206R0\214\004stop\224h\031(h\034(K\001K\000K\001K\002KCC\014t\000\240\001\241\000\001\000d\000S\000\224N\205\224hH\214\nstop_spark\224\206\224h!\205\224h#h}K\034C\002\000\001\224))t\224R\224h\'NNNt\224R\224h/h\207}\224}\224(h)h}h2\214\021SparkCluster.stop\224h4}\224h6Nh7Nh\022h\023h8Nh9Nh:]\224h<}\224hHh]su\206\224\206R0h8Nu}\224\206\224\206R0\205\224}\224\214 f8f3d6e99d06444fa12797d9821a8c48\224Nt\224R\224h\020h\225}\224(\214\023__ray_actor_class__\224h\r\214\021__ray_terminate__\224h\031(h\034(K\001K\000K\002K\002KSC\"t\000j\001j\002}\001|\001j\003t\000j\004k\003r\036t\000j\005\240\006\241\000\001\000d\000S\000\224N\205\224(\214\003ray\224\214\006worker\224\214\rglobal_worker\224\214\004mode\224\214\nLOCAL_MODE\224\214\005actor\224\214\nexit_actor\224t\224h!h\234\206\224\214</home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py\224h\230M\346\003C\006\000\001\010\001\014\001\224))t\224R\224}\224(h(\214\003ray\224h)\214\tray.actor\224h*\214</home/ray/anaconda3/lib/python3.7/site-packages/ray/actor.py\224uNNNt\224R\224h/h\255}\224}\224(h)h\230h2\214-modify_class.<locals>.Class.__ray_terminate__\224h4}\224h6Nh7Nh\022h\252h8Nh9Nh:]\224(hW\214\nray.worker\224\205\224R\224hWh\252\205\224R\224eh<}\224h\233hWh\233\205\224R\224su\206\224\206R0u}\224\206\224\206R0."
  client_ref_id: "\314\217\244\'\005\231\034G\335\242\324\251\240\255\240\003W"
}


```

**Comment by ConeyLiu** [comment]
Your image `seedjeffwan/ray:0.1` has not installed raydp. I think you could have two choices:

1.  Add the raydp into the image, the image should provide the java environments as well.
2. Build the raydp image following the step https://github.com/oap-project/raydp/tree/master/docker

The latest released ray can not scheduler tasks with memory requirements on k8s. We have fixed it in the master branch. If you use the yaml file similar as this https://github.com/oap-project/raydp/blob/master/docker/example.yaml. There are two ways to work around it right now. 
```
Specify the min_workers to your expected one.
Specify the memory in the resource. It should be 70% of the total available memory for the worker node.
```

**Comment by Jeffwan** [comment]
@ConeyLiu Thanks. I actually forget to update my head pod images. 

1. Seems `ray client` is not working as expected. I change to `ray.init(address="auto")` and run the application inside head pod on kubernetes and it's running but still has following error. Looks like it's java runtime related. Do you have recommended java version?  I am using `openjdk 11.0.10 2021-01-19`

```
2021-04-08 14:24:15 ERROR Inbox:94 - An error happened while processing message in the inbox for RAY_APP_MASTER
java.lang.NoSuchMethodError: 'io.ray.api.call.ActorCreator io.ray.api.call.ActorCreator.setJvmOptions(java.lang.String)'
	at org.apache.spark.raydp.AppMasterJavaUtils.createExecutorActor(AppMasterJavaUtils.java:47)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.org$apache$spark$deploy$raydp$RayAppMaster$RayAppMasterEndpoint$$requestNewExecutor(RayAppMaster.scala:190)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.$anonfun$schedule$1(RayAppMaster.scala:177)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.org$apache$spark$deploy$raydp$RayAppMaster$RayAppMasterEndpoint$$schedule(RayAppMaster.scala:176)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint$$anonfun$receive$1.applyOrElse(RayAppMaster.scala:104)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "dispatcher-event-loop-0" java.lang.NoSuchMethodError: 'io.ray.api.call.ActorCreator io.ray.api.call.ActorCreator.setJvmOptions(java.lang.String)'
	at org.apache.spark.raydp.AppMasterJavaUtils.createExecutorActor(AppMasterJavaUtils.java:47)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.org$apache$spark$deploy$raydp$RayAppMaster$RayAppMasterEndpoint$$requestNewExecutor(RayAppMaster.scala:190)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.$anonfun$schedule$1(RayAppMaster.scala:177)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint.org$apache$spark$deploy$raydp$RayAppMaster$RayAppMasterEndpoint$$schedule(RayAppMaster.scala:176)
	at org.apache.spark.deploy.raydp.RayAppMaster$RayAppMasterEndpoint$$anonfun$receive$1.applyOrElse(RayAppMaster.scala:104)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:115)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
21/04/08 14:24:33 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
21/04/08 14:24:48 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
21/04/08 14:25:03 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
21/04/08 14:25:18 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
21/04/08 14:25:33 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
``


2. >  The latest released ray can not scheduler tasks with memory requirements on k8s.

You mean `pod.container.resources.requests/limits.memory` is not supported ? 

I am using raydp 0.2.0 with ray 2.0.0-dev (cluster head & worker) which is the nightly build master.  I think raydp doesn't use ray 2.0.0 as the dependency so I think this problem is still there?

**Comment by ConeyLiu** [comment]
> You mean pod.container.resources.requests/limits.memory is not supported ?

The autoscaler is not supported with memory request scaling. You can ignore it if you don't use autoscaler. And the master branch should work now.

> I am using raydp 0.2.0 with ray 2.0.0-dev (cluster head & worker) which is the nightly build master. I think raydp doesn't use ray 2.0.0 as the dependency so I think this problem is still there?

There are some changes in internal in the master branch, such as here https://github.com/oap-project/raydp/pull/106/files. We have not supported the latest code because it has not been released.

**Comment by Jeffwan** [comment]
@ConeyLiu Thanks for your help! I switch to 1.2.0 and it's working properly.
