### ISSUE TITLE
not stable when using ray client mode

### ISSUE THREAD

**Issue by valiantljk** [oap-project/raydp#135]
I'm using raydp in ray's client mode, trying to submit a raydp operation with ray.remote, 
it works during the initial test, but when I re-run this code, it doesn't print anything, which seems failed quitely.

```
import ray
import raydp
import logging
example_cluster = "xxx.xxx.xxx.xxx:50051" # set this to your ray client address
try:
    ray.util.connect(example_cluster)
    logging.info(f"Connected to pre-provisioned cluster:{example_cluster}")
except Exception as e:
    logging.info(f"Error in client connection:{e}")
    pass

class SparkOp:
    def __init__(self):
        self.spark = None
        self.started = False
    def start(self, config= None):
        try:
            #todo: pass user config into init_spark
            self.spark = raydp.init_spark('word_count',
                                       num_executors=2,
                                       executor_cores=1,
                                       executor_memory='1G')
            self.started = True
        except Exception as e:
            logging.info(f"starting spark failed:{e}")
            self.started = False    

    def run(self, input_data=None):
        if not self.started:
            self.start()
            logging.info("starting spark now...")
        if not self.started:
            logging.info("spark is not started, exit")
            return
        try:
            df = self.spark.createDataFrame([('look',), ('spark',), ('tutorial',), ('spark',), ('look', ), ('python', )], ['word'])
            df.show()
            word_count = df.groupBy('word').count()
            word_count.show()
            logging.info("returnning dataframe")
            #todo: add support for RayFlow Tensor Cache
            #return df.collect() 
        except Exception as e:
            logging.info(f"running spark job failed:{e}, stopping spark now")
            self.stop()
    def stop(self):
        raydp.stop_spark()
        
spark = ray.remote(SparkOp).remote()
ray.get(spark.run.remote())
ray.get(spark.stop.remote())
```

**Comment by valiantljk** [comment]
Example error messages are like:
```
jialin.liu@mlx-engine-dp4coo9bxanc2u-0 ➜ /mlx/data00 python test_spark.py 
INFO:root:Connected to pre-provisioned cluster:10.192.191.15:32192
ERROR:ray.util.client.worker:ray::SparkOp.run() (pid=2550, ip=192.168.77.197)
    print(self._jdf.showString(n, 20, vertical))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/sql/utils.py", line 128, in deco
    return f(*a, **kw)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o76.showString

During handling of the above exception, another exception occurred:

ray::SparkOp.run() (pid=2550, ip=192.168.77.197)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

ray::SparkOp.run() (pid=2550, ip=192.168.77.197)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

ray::SparkOp.run() (pid=2550, ip=192.168.77.197)
  File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "test_spark.py", line 61, in run
  File "test_spark.py", line 63, in stop
  File "/home/ray/anaconda3/lib/python3.7/site-packages/raydp/context.py", line 134, in stop_spark
    _global_spark_context.stop()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/raydp/context.py", line 79, in stop
    self._spark_session.stop()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/sql/session.py", line 707, in stop
    self._jvm.SparkSession.clearDefaultSession()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1695, in __getattr__
    "\n" + proto.END_COMMAND_PART)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1031, in send_command
    connection = self._get_connection()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 979, in _get_connection
    connection = self._create_connection()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 985, in _create_connection
    connection.start()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1127, in start
    raise Py4JNetworkError(msg, e)
py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:39169)
Traceback (most recent call last):
  File "test_spark.py", line 66, in <module>
    ray.get(spark.run.remote())
  File "/opt/mlx_deploy/miniconda3/envs/mlx/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 46, in wrapper
    return getattr(ray, func.__name__)(*args, **kwargs)
  File "/opt/mlx_deploy/miniconda3/envs/mlx/lib/python3.7/site-packages/ray/util/client/api.py", line 33, in get
    return self.worker.get(vals, timeout=timeout)
  File "/opt/mlx_deploy/miniconda3/envs/mlx/lib/python3.7/site-packages/ray/util/client/worker.py", line 156, in get
    out = [self._get(x, timeout) for x in to_get]
  File "/opt/mlx_deploy/miniconda3/envs/mlx/lib/python3.7/site-packages/ray/util/client/worker.py", line 156, in <listcomp>
    out = [self._get(x, timeout) for x in to_get]
  File "/opt/mlx_deploy/miniconda3/envs/mlx/lib/python3.7/site-packages/ray/util/client/worker.py", line 170, in _get
    raise err
types.RayTaskError(Py4JNetworkError): ray::SparkOp.run() (pid=2550, ip=192.168.77.197)
    print(self._jdf.showString(n, 20, vertical))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/sql/utils.py", line 128, in deco
    return f(*a, **kw)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o76.showString

During handling of the above exception, another exception occurred:

ray::SparkOp.run() (pid=2550, ip=192.168.77.197)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

ray::SparkOp.run() (pid=2550, ip=192.168.77.197)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

ray::SparkOp.run() (pid=2550, ip=192.168.77.197)
  File "python/ray/_raylet.pyx", line 473, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "test_spark.py", line 61, in run
  File "test_spark.py", line 63, in stop
  File "/home/ray/anaconda3/lib/python3.7/site-packages/raydp/context.py", line 134, in stop_spark
    _global_spark_context.stop()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/raydp/context.py", line 79, in stop
    self._spark_session.stop()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/sql/session.py", line 707, in stop
    self._jvm.SparkSession.clearDefaultSession()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1695, in __getattr__
    "\n" + proto.END_COMMAND_PART)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1031, in send_command
    connection = self._get_connection()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 979, in _get_connection
    connection = self._create_connection()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 985, in _create_connection
    connection.start()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1127, in start
    raise Py4JNetworkError(msg, e)
py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:39169)
```

**Comment by valiantljk** [comment]
Very often, it just doesn't print anything.

**Comment by valiantljk** [comment]
not sure the issue is from raydp or ray, sometimes i also see the following errors:
```
(raylet) terminate called after throwing an instance of 'std::bad_alloc'
(raylet)   what():  std::bad_alloc
```

**Comment by valiantljk** [comment]
after running the code on ray head with out using ray.util.connect, and not use ray.remote to submit raydp op, 
it seems my code has some issue in accessing hdfs, 
```
>>> df = spark.read.csv(input_data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 538, in csv
    return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/pyspark/sql/utils.py", line 134, in deco
    raise_from(converted)
  File "<string>", line 3, in raise_from
pyspark.sql.utils.IllegalArgumentException: java.net.UnknownHostException
```

This means, once there is an error, ray or raydp didn't capture it well or handle it well, this makes us hard to debug on the client side,

**Comment by ConeyLiu** [comment]
It seems like the error message not forward well by the ray client?

**Comment by hglyou** [comment]
I'm experiencing the same issue here. 
Below is logs from worker nodes 
`	Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1207, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1033, in send_command
    response = connection.send_command(command)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1212, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
`

`

Setting default log level to "WARN".
--
  | To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
  | ERROR:root:Exception while sending command.
  | Traceback (most recent call last):
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1207, in send_command
  | raise Py4JNetworkError("Answer from Java side is empty")
  | py4j.protocol.Py4JNetworkError: Answer from Java side is empty
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1033, in send_command
  | response = connection.send_command(command)
  | File "/home/ray/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1212, in send_command
  | "Error while receiving", e, proto.ERROR_ON_RECEIVE)
  | py4j.protocol.Py4JNetworkError: Error while receiving

`

**Comment by kira-lin** [comment]
close as stale
