### ISSUE TITLE
when i create initialization  twice ray,raydp , An error occurred。

### ISSUE THREAD

**Issue by chinaboyll** [oap-project/raydp#175]
My version:
Ray Cluster:1.3.0
Raydp:0.3.0
Python: 3.6.4
when i create initialization  twice ray,raydp , An error occurred。
-----------------
Caused by: java.net.BindException: Address already in use (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:375)
        at py4j.GatewayServer.startSocket(GatewayServer.java:786)
-----------------
I set config configs={"spark.ui.port":"xxx"}

**Comment by carsonwang** [comment]
You only need to init once. If you see this error, it is because the pervious driver is not closed properly. You can find the Java process ID and kill it.

**Comment by Bowen0729** [comment]
> You only need to init once. If you see this error, it is because the pervious driver is not closed properly. You can find the Java process ID and kill it.

What if I want to start two spark driver on the same time? What should I do?

**Comment by carsonwang** [comment]
@Bowen0729 , can you please share more about your use case and requirement?

**Comment by Bowen0729** [comment]
Two users both user raydp in the same conda environment, one of them throw exception address already in use

**Comment by Bowen0729** [comment]
> @Bowen0729 , can you please share more about your use case and requirement?

The Java Gateway port is always 25333, why not a random port?

**Comment by carsonwang** [comment]
This sounds like an issue. So two users will run their Spark driver on the same node and connect to the same Ray cluster, right? Are you interested in submitting a PR for this?

**Comment by Bowen0729** [comment]
> This sounds like an issue. So two users will run their Spark driver on the same node and connect to the same Ray cluster, right? Are you interested in submitting a PR for this?

Sure, I will submit a PR recently. Thank you for your reply

**Comment by carsonwang** [comment]
Great! Thanks!

**Comment by pang-wu** [comment]
@Bowen0729 @carsonwang In this case how do we distinguish the user call `init_spark` twice by mistake or by intention?

**Comment by Bowen0729** [comment]
> 

It's a issue about the java gateway always starts with the default port, so when user call init_spark twice in different session,  the new java gateway cannot start. 

when user call init_spark in the same session, raydp will throw "The spark environment has inited".

**Comment by Hoeze** [comment]
+1 on that issue. It's annoying since we are possibly running multiple ray+raydp instances on the same host...
Especially when there are multiple users!

**Comment by kira-lin** [comment]
close as stale. fixed
