### ISSUE TITLE
raydp.init_spark() failed

### ISSUE THREAD

**Issue by Second222None** [oap-project/raydp#181]
Can anyone help me?
```
(base) [root@master ray]# java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

(base) [root@master ray]# pip list | grep ray
bitarray                           2.1.0
ray                                1.2.0
raydp                              0.1.1

(base) [root@master ray]# pyspark --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.0.3
      /_/

Using Scala version 2.12.10, Java HotSpot(TM) 64-Bit Server VM, 1.8.0_151
Branch HEAD
Compiled by user ubuntu on 2021-06-17T04:52:32Z
Revision 65ac1e75dc468f53fc778cd2ce1ba3f21067aab8
Url https://github.com/apache/spark
Type --help for more information.
```

```java
(base) [root@master ray]# python sparkonray.py
2021-09-29 15:16:16,642 INFO services.py:1172 -- View the Ray dashboard at http://127.0.0.1:8265
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.spark.deploy.raydp.AppMasterEntryPoint.main(AppMasterEntryPoint.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more
Traceback (most recent call last):
  File "sparkonray.py", line 26, in <module>
    spark = raydp.init_spark('word_count',
  File "/root/anaconda3/lib/python3.8/site-packages/raydp/context.py", line 122, in init_spark
    return _global_spark_context.get_or_create_session()
  File "/root/anaconda3/lib/python3.8/site-packages/raydp/context.py", line 68, in get_or_create_session
    spark_cluster = self._get_or_create_spark_cluster()
  File "/root/anaconda3/lib/python3.8/site-packages/raydp/context.py", line 62, in _get_or_create_spark_cluster
    self._spark_cluster = SparkCluster()
  File "/root/anaconda3/lib/python3.8/site-packages/raydp/spark/ray_cluster.py", line 31, in __init__
    self._set_up_master(None, None)
  File "/root/anaconda3/lib/python3.8/site-packages/raydp/spark/ray_cluster.py", line 37, in _set_up_master
    self._app_master_bridge.start_up()
  File "/root/anaconda3/lib/python3.8/site-packages/raydp/spark/ray_cluster_master.py", line 52, in start_up
    self._gateway = self._launch_gateway(extra_classpath, popen_kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/raydp/spark/ray_cluster_master.py", line 115, in _launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number
```

**Comment by kira-lin** [comment]
Hi @Second222None , I notice you are using a quite old version of ray and raydp. Is it possible for you to try latest stable versions? Because pyspark 3.0.3 is not released at that time, it is possible that they are not compatible.

**Comment by Second222None** [comment]
It doesn't help. The same error with the following versions.
```
(base) [root@master ray]# pip list | grep ray
bitarray                           2.1.0
ray                                1.6.0
raydp                              0.3.0
```

**Comment by kira-lin** [comment]
The error message shows that org.apache.spark.internal.Logging is not found when the raydp starts, so it should be a problem with classpath. Is pyspark properly installed? You can try to add `print(classpath)` to the start of `_launch_gateway` function in "/root/anaconda3/lib/python3.8/site-packages/raydp/spark/ray_cluster_master.py". And run again to see what is print.

**Comment by Second222None** [comment]
It looks like so:
```
(base) [root@master ray]# python sparkonray.py
2021-09-29 16:16:39,584 INFO services.py:1267 -- View the Ray dashboard at http://127.0.0.1:8265
class_path =  /root/anaconda3/lib/python3.8/site-packages/raydp/jars/*:/root/anaconda3/lib/python3.8/site-packages/ray/jars/*
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging
        at java.lang.ClassLoader.defineClass1(Native Method)
```

**Comment by kira-lin** [comment]
So pyspark's directory is not found. That's the reason for the error, can you please print out the variables in `_prepare_jvm_classpath` similarly to debug the problem? Can pyspark be imported in your program?

**Comment by Second222None** [comment]
`spark_jars` is empty.
```
(base) [root@master ray]# python sparkonray.py
2021-09-29 18:01:45,326 INFO services.py:1267 -- View the Ray dashboard at http://127.0.0.1:8265
spark_home =  /home/spark-3.0.3-bin-hadoop2.7/python/pyspark
spark_jars_dir =  /home/spark-3.0.3-bin-hadoop2.7/python/pyspark/jars/*
spark_jars =  []
class_path =  /root/anaconda3/lib/python3.8/site-packages/raydp/jars/*:/root/anaconda3/lib/python3.8/site-packages/ray/jars/*
```

**Comment by Second222None** [comment]
Thank you! Problem solved. There is no `jars` in spark  directory, instead , it resides in `anaconda3/lib` directory. I don't remember the installation history very clearly.
```
cp -rf /root/anaconda3/lib/python3.8/site-packages/pyspark-3.0.3-py3.8.egg/pyspark/jars /home/spark-3.0.3-bin-hadoop2.7/python/pyspark
```

Long-awaited results：
```
(base) [root@master ray]# python sparkonray.py
2021-09-29 18:28:39,315 INFO services.py:1267 -- View the Ray dashboard at http://127.0.0.1:8265
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2021-09-29 18:28:43 WARN  NativeCodeLoader:60 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2021-09-29 18:28:45,970 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
+--------+
|    word|
+--------+
|    look|
|   spark|
|tutorial|
|   spark|
|    look|
|  python|
+--------+

+--------+-----+
|    word|count|
+--------+-----+
|tutorial|    1|
|   spark|    2|
|    look|    2|
|  python|    1|
+--------+-----+
```

**Comment by kira-lin** [comment]
Glad you solve the problem. Post a issue whenever you have a question again.
