### ISSUE TITLE
Cannot Initialize Spark with RayDP

### ISSUE THREAD

**Issue by Alan-Penkar** [oap-project/raydp#225]
I'm trying to use RayDP with Spark, and having trouble getting it initialized with the sample code in the documentation.  My code and error is below, I'm on Spark 3.2.1, Python 3.7.11, Ray 1.11.0, Raydp 0.4.1.  I'm not sure if there is a version issue or there's something missing from the documentation, so any help would be appreciated.

Code below is running on Debian in Docker

``` python
import pyspark
import ray
import raydp

ray.init()
spark = raydp.init_spark(app_name='RayDP Example',
                         num_executors=1,
                         executor_cores=1,
                         executor_memory='4GB')
```
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/raydp/context.py", line 126, in init_spark
    return _global_spark_context.get_or_create_session()
  File "/usr/local/lib/python3.7/site-packages/raydp/context.py", line 70, in get_or_create_session
    spark_cluster = self._get_or_create_spark_cluster()
  File "/usr/local/lib/python3.7/site-packages/raydp/context.py", line 63, in _get_or_create_spark_cluster
    self._spark_cluster = SparkCluster(self._configs)
  File "/usr/local/lib/python3.7/site-packages/raydp/spark/ray_cluster.py", line 34, in __init__
    self._set_up_master(None, None)
  File "/usr/local/lib/python3.7/site-packages/raydp/spark/ray_cluster.py", line 40, in _set_up_master
    self._app_master_bridge.start_up()
  File "/usr/local/lib/python3.7/site-packages/raydp/spark/ray_cluster_master.py", line 56, in start_up
    self._set_properties()
  File "/usr/local/lib/python3.7/site-packages/raydp/spark/ray_cluster_master.py", line 158, in _set_properties
    self._app_master_java_bridge.setProperties(jvm_properties)
  File "/usr/local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o0.setProperties.
: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at java.base/java.util.Properties.put(Properties.java:1340)
	at java.base/java.util.Properties.setProperty(Properties.java:228)
	at java.base/java.lang.System.setProperty(System.java:898)
	at org.apache.spark.deploy.raydp.AppMasterJavaBridge.$anonfun$setProperties$1(AppMasterJavaBridge.scala:32)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:400)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
	at org.apache.spark.deploy.raydp.AppMasterJavaBridge.setProperties(AppMasterJavaBridge.scala:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by kira-lin** [comment]
@Alan-Penkar , yes, as I tested, ray 1.10.x should work.
