### ISSUE TITLE
Failed to initialize a Spark session with Ray 2.3

### ISSUE THREAD

**Issue by chenya-zhang** [oap-project/raydp#324]
Environment: 
RayDP 1.5.0, Python 3.7, k8s 1.22, open-jdk 11

Observation:
RayDP 1.5.0 + Ray 2.2 works well.

RayDP 1.5.0 + Ray 2.3 throws the below NPE exception when initializing a Spark session following https://github.com/oap-project/raydp#spark-on-ray.

```
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.deploy.raydp.RayAppMaster.setProperties.
: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at java.base/java.util.Properties.put(Properties.java:1340)
	at java.base/java.util.Properties.setProperty(Properties.java:228)
	at java.base/java.lang.System.setProperty(System.java:905)
	at org.apache.spark.deploy.raydp.RayAppMaster$.$anonfun$setProperties$1(RayAppMaster.scala:336)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:400)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
	at org.apache.spark.deploy.raydp.RayAppMaster$.setProperties(RayAppMaster.scala:335)
```

I did a quick search - it seems to pass in ray/jvm properties with a null key/value (https://github.com/oap-project/raydp/blob/v1.5.0/core/raydp-main/src/main/scala/org/apache/spark/deploy/raydp/RayAppMaster.scala#L336)

Not sure if this is a known issue when working with Ray 2.3?

Thanks!

**Comment by pjsulin** [comment]
I'm having the same problem with 1.5 and using the nightly build 1.6.0b20230331.dev0. 

Full stack trace:

2023-03-31 08:42:30,814	INFO worker.py:1553 -- Started a local Ray instance.
(pid=10016) 
(RayDPSparkMaster pid=10029) ERROR StatusLogger Reconfiguration failed: No configuration found for '7c53a9eb' at 'null' in 'null'
(RayDPSparkMaster pid=10029) ERROR StatusLogger Reconfiguration failed: No configuration found for 'Default' at 'null' in 'null'
(RayDPSparkMaster pid=10029) Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
2023-03-31 08:42:36,756	WARNING worker.py:1866 -- Traceback (most recent call last):
  File "python/ray/_raylet.pyx", line 850, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 902, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 857, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 861, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 803, in ray._raylet.execute_task.function_executor
  File "/Users/psulin/.pyenv/versions/dbtool/lib/python3.10/site-packages/ray/_private/function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/Users/psulin/.pyenv/versions/dbtool/lib/python3.10/site-packages/ray/util/tracing/tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "/Users/psulin/.pyenv/versions/dbtool/lib/python3.10/site-packages/raydp/spark/ray_cluster_master.py", line 71, in start_up
    self._gateway.jvm.org.apache.spark.deploy.raydp.RayAppMaster.setProperties(ray_properties)
  File "/Users/psulin/.pyenv/versions/dbtool/lib/python3.10/site-packages/py4j/java_gateway.py", line 1321, in __call__
    return_value = get_return_value(
  File "/Users/psulin/.pyenv/versions/dbtool/lib/python3.10/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.deploy.raydp.RayAppMaster.setProperties.
: java.lang.NoClassDefFoundError: io/ray/runtime/config/RayConfig
	at org.apache.spark.deploy.raydp.RayAppMaster$.setProperties(RayAppMaster.scala:339)
	at org.apache.spark.deploy.raydp.RayAppMaster.setProperties(RayAppMaster.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: io.ray.runtime.config.RayConfig
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more

**Comment by kira-lin** [comment]
Can you please verify if the ray jar is presented under /path-to-installed-ray/jars?

**Comment by kira-lin** [comment]
glad you solved the problem :smile:

**Comment by peterghaddad** [comment]
@kira-lin are the following errors normal when running the nightly raydp and ray 2.3?

```
(RayDPSparkMaster pid=10029) ERROR StatusLogger Reconfiguration failed: No configuration found for '7c53a9eb' at 'null' in 'null'
(RayDPSparkMaster pid=10029) ERROR StatusLogger Reconfiguration failed: No configuration found for 'Default' at 'null' in 'null'
```

**Comment by kira-lin** [comment]
I didn't see this error in my environment. Do you have problem with nightly raydp?

**Comment by peterghaddad** [comment]
@kira-lin I did when I created the issue, but looks like not anymore.

When does raydp plan on cutting a new release and will it be compatible with Ray 2.3.x? Thanks!

**Comment by kira-lin** [comment]
OK. We'll try to make a release soon
