### ISSUE TITLE
Can't init spark on multi-nodes ray cluster on k8s

### ISSUE THREAD

**Issue by valiantljk** [oap-project/raydp#76]
Hi I was able to run raydp on my laptop and on K8S (by initializing a single node ray cluster, e.g., ray.init()), 
but on K8S, if I run raydp by connecting to a multi-node existing ray cluster, e.g., ray.init(address="auto"), I got the errors, and ray head will crash.

Here is my test code:
```
import ray,raydp
ray.init(address="auto")
raydp.init_spark(app_name, num_executors, cores_per_executor, memory_per_executor)
```

```
(base) root@ray-head-7f4bc4b6df-nx697:/ray-raydp# python spark_init.py 1
2020-12-23 13:14:59,426	INFO worker.py:655 -- Connecting to existing Ray cluster at address: 10.40.1.13:6379
number of workers:1
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/ray-raydp/ray/python/ray/jars/ray_dist.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/anaconda3/lib/python3.7/site-packages/pyspark/jars/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
(pid=raylet) [2020-12-23 13:15:01,006 C 35 35] worker_pool.cc:952:  Check failed: state != states_by_lang_.end() Required Language isn't supported.
(pid=raylet) [2020-12-23 13:15:01,006 E 35 35] logging.cc:414: *** Aborted at 1608758101 (unix time) try "date -d @1608758101" if you are using GNU date ***
(pid=raylet) [2020-12-23 13:15:01,006 E 35 35] logging.cc:414: PC: @                0x0 (unknown)
(pid=raylet) [2020-12-23 13:15:01,006 E 35 35] logging.cc:414: *** SIGABRT (@0x23) received by PID 35 (TID 0x7f14e82f7800) from PID 35; stack trace: ***
(pid=raylet) [2020-12-23 13:15:01,006 E 35 35] logging.cc:414:     @     0x556a2af32d97 google::(anonymous namespace)::FailureSignalHandler()
(pid=raylet) [2020-12-23 13:15:01,007 E 35 35] logging.cc:414:     @     0x7f14e85293c0 (unknown)
(pid=raylet) [2020-12-23 13:15:01,007 E 35 35] logging.cc:414:     @     0x7f14e834218b gsignal
(pid=raylet) [2020-12-23 13:15:01,007 E 35 35] logging.cc:414:     @     0x7f14e8321859 abort
(pid=raylet) [2020-12-23 13:15:01,007 E 35 35] logging.cc:414:     @     0x556a2a9e00ad _ZN3ray6RayLogD2Ev.cold
(pid=raylet) [2020-12-23 13:15:01,009 E 35 35] logging.cc:414:     @     0x556a2aa66a3c ray::raylet::WorkerPool::GetStateForLanguage()
(pid=raylet) [2020-12-23 13:15:01,010 E 35 35] logging.cc:414:     @     0x556a2aa6e003 ray::raylet::WorkerPool::RegisterDriver()
(pid=raylet) [2020-12-23 13:15:01,012 E 35 35] logging.cc:414:     @     0x556a2aac9096 ray::raylet::NodeManager::ProcessRegisterClientRequestMessage()
(pid=raylet) [2020-12-23 13:15:01,014 E 35 35] logging.cc:414:     @     0x556a2aadcce2 ray::raylet::NodeManager::ProcessClientMessage()
(pid=raylet) [2020-12-23 13:15:01,014 E 35 35] logging.cc:414:     @     0x556a2aa29625 _ZNSt17_Function_handlerIFvSt10shared_ptrIN3ray16ClientConnectionEElRKSt6vectorIhSaIhEEEZNS1_6raylet6Raylet12HandleAcceptERKN5boost6system10error_codeEEUlS3_lS8_E0_E9_M_invokeERKSt9_Any_dataOS3_OlS8_
(pid=raylet) [2020-12-23 13:15:01,015 E 35 35] logging.cc:414:     @     0x556a2ae81792 ray::ClientConnection::ProcessMessage()
(pid=raylet) [2020-12-23 13:15:01,016 E 35 35] logging.cc:414:     @     0x556a2ae7eabc boost::asio::detail::reactive_socket_recv_op<>::do_complete()
(pid=raylet) [2020-12-23 13:15:01,016 E 35 35] logging.cc:414:     @     0x556a2b26b701 boost::asio::detail::scheduler::do_run_one()
(pid=raylet) [2020-12-23 13:15:01,017 E 35 35] logging.cc:414:     @     0x556a2b26ce41 boost::asio::detail::scheduler::run()
(pid=raylet) [2020-12-23 13:15:01,019 E 35 35] logging.cc:414:     @     0x556a2b26f4bb boost::asio::io_context::run()
(pid=raylet) [2020-12-23 13:15:01,020 E 35 35] logging.cc:414:     @     0x556a2a9fbdc2 main
(pid=raylet) [2020-12-23 13:15:01,020 E 35 35] logging.cc:414:     @     0x7f14e83230b3 __libc_start_main
(pid=raylet) [2020-12-23 13:15:01,022 E 35 35] logging.cc:414:     @     0x556a2aa1189e _start
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1207, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1033, in send_command
    response = connection.send_command(command)
  File "/root/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1212, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
An error occurred while calling o0.startUpAppMaster
ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 977, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1115, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by valiantljk** [comment]
It might be this:

AppMasterJavaBridge.scala
```
  def startUpAppMaster(extra_cp: String): Unit = {
    if (instance == null) {
      // init ray, we should set the config by java properties
      Ray.init()
      instance = new RayAppMaster(extra_cp)
    }
  }
```

**Comment by valiantljk** [comment]
By looking at Ray's [Java API](https://github.com/ray-project/ray/blob/master/java/runtime/src/main/resources/ray.default.conf), it looks like we need to use ray.conf to modify the address

**Comment by valiantljk** [comment]
I tried to set the address like this:

```
  def startUpAppMaster(extra_cp: String): Unit = {
    if (instance == null) {
      System.setProperty("ray.address", "auto")
      // init ray, we should set the config by java properties
      Ray.init()
      instance = new RayAppMaster(extra_cp)
    }
  }
```

Still same error.

**Comment by ConeyLiu** [comment]
hi @valiantljk, could you try #77 this? It works for me on k8s (1 master node, 2 worker nodes). 
Also cc @carsonwang

**Comment by tkram01** [comment]
I am getting a similar error. I am using the Ray AWS cluster launcher. When I run a raydp program it acts like it is using a local ray instance and trying to launch the workers on the head node instead of on the worker nodes. Eventually the head node crashes from running out of memory. Here is my config for the Ray cluster launcher.

```# An unique identifier for the head node and workers of this cluster.
cluster_name: minimal

max_workers: 3

idle_timeout_minutes: 5

worker_nodes:
    InstanceType: t3.xlarge
    ImageId: ami-0996d3051b72b5b2c

head_node:
    InstanceType: t3.small
    ImageId: ami-0996d3051b72b5b2c

provider:
    type: aws
    region: us-east-2
    availability_zone: us-east-2a

auth:
    ssh_user: ubuntu

setup_commands: ["pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl", "pip install -U raydp dask[complete]"]
initialization_commands: ["sudo apt update -y", "sudo apt-get -y install python3 default-jdk", "sudo apt-get install -y python3-pip", "sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1", "sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1", "pip install boto3"]
```

and the code I am trying to execute under ray

```import ray
import raydp

ray.init(address='auto')

@ray.remote
class PySparkDriver:
  def __init__(self):
    self.spark = raydp.init_spark(
        app_name='RayDP example',
        num_executors=10,
        executor_cores=1,
        executor_memory=471859200)

  def foo(self):
    return self.spark.range(1000000).repartition(1000).count()

driver = PySparkDriver.remote()
print(ray.get(driver.foo.remote()))
raydp.stop_spark()```

**Comment by ConeyLiu** [comment]
Hi @tkram01, could you take a try the following?
```python
import ray
import raydp

ray.init(address='auto')

@ray.remote
class PySparkDriver:
  def __init__(self):
    assert ray.is_initialized()
    self.spark = raydp.init_spark(
        app_name='RayDP example',
        num_executors=10,
        executor_cores=1,
        executor_memory="2GB")

  def foo(self):
    return self.spark.range(1000000).repartition(1000).count()

  def stop(self):
    raydp.stop_spark()

driver = PySparkDriver.remote()
print(ray.get(driver.foo.remote()))
ray.get(driver.stop.remote())
```

**Comment by tkram01** [comment]
@ConeyLiu I get the similar behavior with your code. With the increased value for executor_memory I get these messages when monitoring.

```======== Autoscaler status: 2021-02-22 01:11:35.636059 ========
Node status
---------------------------------------------------------------
Healthy:
 1 ray-legacy-head-node-type
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------

Usage:
 0.0/2.0 CPU
 0.00/0.977 GiB memory
 0.00/0.342 GiB object_store_memory

Demands:
 {'memory': 41.0, 'CPU': 1.0}: 10+ pending tasks/actors
2021-02-22 01:11:40,847	WARNING resource_demand_scheduler.py:642 -- The autoscaler could not find a node type to satisfy the request: [{'CPU': 1.0, 'memory': 41.0}, {'CPU': 1.0, 'memory': 41.0}, {'CPU': 1.0, 'memory': 41.0}, {'CPU': 1.0, 'memory': 41.0}, {'CPU': 1.0, 'memory': 41.0}, {'CPU': 1.0, 'memory': 41.0}, {'CPU': 1.0, 'memory': 41.0}, {'CPU': 1.0, 'memory': 41.0}, {'CPU': 1.0, 'memory': 41.0}, {'CPU': 1.0, 'memory': 41.0}]. If this request is related to placement groups the resource request will resolve itself, otherwise please specify a node type with the necessary resource https://docs.ray.io/en/master/cluster/autoscaling.html#multiple-node-type-autoscaling.
```

If I am reading this correctly it is trying to create a worker with 41GB of RAM and my worker nodes only have 16GB. I'm not sure why this would ever be above the 2GB configured in spark_init. In any case it still tries to run on the head node until is runs out of memory.

**Comment by ConeyLiu** [comment]
@tkram01 Does this get the same errors on ray 1.1.0?

**Comment by tkram01** [comment]
@ConeyLiu I see similar behavior on 1.1.0

```2021-02-22 13:27:35,625	INFO resource_demand_scheduler.py:148 -- Cluster resources: [{'memory': 20.0, 'node:172.31.12.88': 1.0, 'CPU': 2.0, 'object_store_memory': 7.0}]
2021-02-22 13:27:35,625	INFO resource_demand_scheduler.py:149 -- Node counts: defaultdict(<class 'int'>, {'ray-legacy-head-node-type': 1})
2021-02-22 13:27:35,625	INFO resource_demand_scheduler.py:159 -- Placement group demands: []
2021-02-22 13:27:35,625	INFO resource_demand_scheduler.py:186 -- Resource demands: [{'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}]
2021-02-22 13:27:35,626	INFO resource_demand_scheduler.py:187 -- Unfulfilled demands: [{'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}]
2021-02-22 13:27:35,626	INFO resource_demand_scheduler.py:604 -- No feasible node type to add for [{'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}, {'memory': 41.0, 'CPU': 1.0}]
2021-02-22 13:27:35,626	INFO resource_demand_scheduler.py:209 -- Node requests: {}
```

**Comment by ConeyLiu** [comment]
Very strange.  I will take a look at this.

**Comment by Second222None** [comment]
> Hi @tkram01, could you take a try the following?
> 
> ```python
> import ray
> import raydp
> 
> ray.init(address='auto')
> 
> @ray.remote
> class PySparkDriver:
>   def __init__(self):
>     assert ray.is_initialized()
>     self.spark = raydp.init_spark(
>         app_name='RayDP example',
>         num_executors=10,
>         executor_cores=1,
>         executor_memory="2GB")
> 
>   def foo(self):
>     return self.spark.range(1000000).repartition(1000).count()
> 
>   def stop(self):
>     raydp.stop_spark()
> 
> driver = PySparkDriver.remote()
> print(ray.get(driver.foo.remote()))
> ray.get(driver.stop.remote())
> ```

I run the code above successfully.
How can I check whether Spark is scheduled to multiple nodes?

**Comment by kira-lin** [comment]
You can check the spark UI at port 4040 to see executors' IP. Or you can check ray's dashboard (default 8265) to see which actor is on which node, etc.

**Comment by kira-lin** [comment]
close as stale
