### ISSUE TITLE
model.train() reports an error when running estimator.fit_on_spark(df)

### ISSUE THREAD

**Issue by Matrix-World** [oap-project/raydp#94]
Thanks to the author's efforts, this is a very good project. 
I tried to run the following brief test program. 
------------code-------------
import raydp
from raydp.torch import TorchEstimator
#start Spark job on Ray
spark = raydp.init_spark(
  app_name = "example test",
  num_executors = 3,
  executor_cores = 3,
  executor_memory="10GB"
)
##prepare the data
customers =  [(1,'James',21,6), (2, "Liz",25,8), (3, "John", 31, 6),\
     (4, "Jennifer", 45, 7), (5, "Robert", 41, 5), (6, "Sandra", 45, 8)]
df = spark.createDataFrame(customers, ["cID", "name", "age", "grade"])
df.show()

import torch
##create model
model = torch.nn.Sequential(torch.nn.Linear(2, 1))
optimizer = torch.optim.Adam(model.parameters())
loss = torch.nn.MSELoss()
#config
estimator = TorchEstimator(
  model = model,
  optimizer = optimizer,
  loss = loss,
  num_workers = 3,
  num_epochs = 5,
  feature_columns = ["age"],
  label_column = ["grade"]
)
print("before fit on spark, the type of model:", type(model))
estimator.fit_on_spark(df)
##get the trained model
pytorch_model = estimator.get_model()
------------code-------------
But when performing model training model.train() in training_operator.py, an error message was reported: AttributeError:'list' object has no attribute'train'.
--------error-----------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.7/site-packages/raydp/torch/estimator.py", line 311, in fit_on_spark
    train_ds, evaluate_ds, num_steps, profile, reduce_results, max_retries, info)
  File "/root/miniconda3/lib/python3.7/site-packages/raydp/torch/estimator.py", line 284, in fit
    info=info)
  File "/root/miniconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_trainer.py", line 410, in train
    num_steps=num_steps, profile=profile, info=info, dataset=dataset)
  File "/root/miniconda3/lib/python3.7/site-packages/ray/util/sgd/torch/worker_group.py", line 325, in train
    success = check_for_failure(remote_worker_stats)
  File "/root/miniconda3/lib/python3.7/site-packages/ray/util/sgd/utils.py", line 244, in check_for_failure
    finished = ray.get(finished)
  File "/root/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1379, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(AttributeError): ray::DistributedTorchRunner.train_epoch() (pid=54182, ip=10.3.68.117)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 415, in ray._raylet.execute_task.function_executor
  File "/root/miniconda3/lib/python3.7/site-packages/ray/util/sgd/torch/distributed_torch_runner.py", line 112, in train_epoch
    num_steps=num_steps, profile=profile, info=info, iterator=iterator)
  File "/root/miniconda3/lib/python3.7/site-packages/ray/util/sgd/torch/torch_runner.py", line 140, in train_epoch
    train_stats = self.training_operator.train_epoch(iterator, info)
  File "/root/miniconda3/lib/python3.7/site-packages/ray/util/sgd/torch/training_operator.py", line 504, in train_epoch
    model.train()
AttributeError: 'list' object has no attribute 'train'
--------error-----------
I was confused, and then executed output before mode.train( line 504 in training_operator.py): print(type(model)), and found that the output was: <class'list'>.
But I executed output after model = outer._model(line 174 in estimator.py): print(type(model)), and found that the output was: <class'torch.nn.modules.container.Sequential'>.
It seems that the type of model has changed.
But I cannot see the specific process of the change, can you help me solve it?
You can run the above program directly.
Looking forward to your reply~~

**Comment by ConeyLiu** [comment]
Hi @Matrix-World, which version of ray and raydp are you using? And the exception was raised on `estimator.fit` step?

**Comment by Matrix-World** [comment]
> Hi @Matrix-World, which version of ray and raydp are you using? And the exception was raised on `estimator.fit` step?

yes, 
ray.__version__ = '1.1.0'
raydp.__version__ = '0.1.1'

**Comment by ConeyLiu** [comment]
Hi @Matrix-World, this is a bug from ray. I have patched (https://github.com/ray-project/ray/issues/14352) to upstream. Maybe you can take a try.

**Comment by ConeyLiu** [comment]
@kira-lin, pls help to fix this in raydp too.

**Comment by Matrix-World** [comment]
I get it, thank you~
